### ISSUE TITLE
Chapter 9: Getting the Data: 403 Forbidden results

### ISSUE THREAD

**Issue by paul-reiners** [sryza/aas#121] opened 2018-03-01 15:08 UTC
When I run

`$ ./download-all-symbols.sh
`

as given on page 199 of the second edition, I get multiple errors of this type:

```
--2018-03-01 09:02:15--  http://www.google.com/finance/historical?q=AAON&startdate=Jan+01%2C+2000&enddate=Dec+31%2C+2013&output=csv
Resolving www.google.com... 172.217.5.228, 2607:f8b0:400d:c0b::68
Connecting to www.google.com|172.217.5.228|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2018-03-01 09:02:15 ERROR 403: Forbidden.

```

**Comment by srowen** [comment] 2018-03-01 15:59
Hm. I'm afraid maybe this source of financial data is also now unavailable. If you request in the browser it says:

We're sorry...
... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

@sryza you don't happen to have a copy of the CSV data from any point in the past that we could just provide a copy of?

**Comment by sryza** [comment] 2018-03-01 19:15
@srowen I do have a copy - any thoughts on the best way to provide it? Is that allowed?

**Comment by paul-reiners** [comment] 2018-03-01 19:32
Would it be possible to simply update the shell script to query another financial data provider that doesn't disallow this sort of thing?  Any static CSV file will quickly be out of date.  Also, people might want to change some of the instruments that are downloaded.  (Actually, that's something I want to do.)

**Comment by srowen** [comment] 2018-03-01 20:50
@sryza are they small enough to just check in here? otherwise I can throw them on a personal cloud bucket or something.

@paul-reiners heh, the problem is we already lost Yahoo Finance, so may be a repeating problem. The actual data doesn't matter so much to the example. You could always swap in your own data in any event.

**Comment by sryza** [comment] 2018-03-02 22:33
@srowen It looks like with the full set of stocks, it's ~70MB. What do you think?

**Comment by srowen** [comment] 2018-03-03 00:04
@sryza I'd do it. It's not a big overhead for people checking out the repo once in a while. Certainly compress it if you can. If there's any issue, I can easily host on my bucket.

**Comment by sryza** [comment] 2018-03-07 05:39
Cool, I committed the files under the `ch09-risk/data` directory. Enjoy!

**Closed by sryza** 2018-03-07 05:39 UTC
